### ISSUE TITLE
Add Note at End of Nexus Setup to Not Login Until After the Rest of the Guide Has Been Run

### ISSUE THREAD

**Issue by ryanrichter94** [chocolatey/choco-quickstart-scripts#165] opened 2022-10-28 13:58 UTC
## Is Your Feature Request Related To A Problem? Please describe.
The following is displayed in prompt after Step 2: Nexus Setup has been run:
```
    ##############################################################

    Nexus Repository Setup Completed
    Please login to the following URL to complete admin account setup:

    Server Url: 'http://localhost:8081' (this will change once you add a certificate)
    Chocolatey Repo: "http://localhost:8081/repository/ChocolateyInternal/"
    NuGet ApiKey: ApiKey value
    Nexus 'admin' user password: Password value

    ##############################################################
```
If the user logs into Nexus at this point the admin.password file for Nexus is deleted. This file is used for further invoking of the Nexus API in the SSL Setup step, as well as the default password being posted to the README after Step 5: Jenkins Setup is run. 

## Describe The Solution. Why is it needed?
A warning should de displayed to instruct users not to login to Nexus until after the README has been generated in Step 5: Jenkins Setup of the guide.

## Additional Context.

NA

## Related Issues
NA

**Comment by JPRuskin** [comment] 2023-07-06 14:29
Is this a duplicate of #161?

**Closed** 2023-07-06 14:30 UTC
Labels: Enhancement, Duplicate Issue
